import type { Metadata } from "next";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { listBillingOperations } from "@/lib/billing/service";

export const metadata: Metadata = { title: "Billing | Backoffice", robots: { index: false, follow: false } };
function amount(value: string, currency: string) { return new Intl.NumberFormat("es", { style: "currency", currency }).format(Number(value)); }

export default async function AdminBillingPage() {
  const operations = await listBillingOperations();
  return <main id="main-content" className="mx-auto max-w-7xl space-y-8 px-4 py-10 sm:px-6 sm:py-14"><div className="space-y-3"><p className="font-mono text-xs uppercase tracking-[0.14em] text-primary">Billing operations</p><h1 className="text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Entitlements y refunds</h1><p className="max-w-3xl text-sm text-muted-foreground">Acceso derivado de pagos confirmados, reembolsos idempotentes y trazabilidad de provider.</p></div><div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle>{operations.refunds.length} reembolsos recientes</CardTitle><CardDescription>Las solicitudes se procesan mediante jobs con reintentos.</CardDescription></CardHeader><CardContent><div className="divide-y divide-border/70">{operations.refunds.length === 0 ? <p className="py-8 text-sm text-muted-foreground">Sin reembolsos.</p> : operations.refunds.map((refund) => <div key={refund.id} className="py-4"><div className="flex items-center justify-between gap-3"><p className="font-medium">{amount(String(refund.amount), refund.currency)}</p><Badge variant={refund.status === "succeeded" ? "default" : "secondary"}>{refund.status}</Badge></div><p className="mt-1 font-mono text-[11px] text-muted-foreground">{refund.id} · order {refund.orderId}</p><p className="mt-1 text-xs text-muted-foreground">{refund.reason ?? "Sin motivo"}{refund.providerRefundId ? ` · ${refund.providerRefundId}` : ""}</p>{refund.lastError ? <p className="mt-2 text-xs text-destructive">{refund.lastError}</p> : null}</div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>{operations.entitlements.length} entitlements recientes</CardTitle><CardDescription>Un grant por orden; un reembolso total lo revoca.</CardDescription></CardHeader><CardContent><div className="divide-y divide-border/70">{operations.entitlements.length === 0 ? <p className="py-8 text-sm text-muted-foreground">Sin entitlements.</p> : operations.entitlements.map((entitlement) => <div key={entitlement.id} className="py-4"><div className="flex items-center justify-between gap-3"><p className="font-mono text-xs">{entitlement.key}</p><Badge variant={entitlement.status === "active" ? "default" : "outline"}>{entitlement.status}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{entitlement.workspaceId ? `workspace ${entitlement.workspaceId}` : `user ${entitlement.userId}`} · order {entitlement.sourceOrderId}</p></div>)}</div></CardContent></Card></div></main>;
}
