"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Price = { id: string; provider: string; amount: string; currency: string; interval: string | null; externalId: string | null; active: boolean; version: number };
type Product = { id: string; name: string; slug: string; description: string | null; active: boolean; version: number; workspaceName: string | null; prices: Price[] };

async function expectOk(response: Response) { const body = (await response.json()) as { error?: string }; if (!response.ok) throw new Error(body.error ?? "No se pudo completar la operación"); }

export function ProductCreateForm() {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); const form = event.currentTarget; const data = new FormData(form); try { const response = await fetch("/api/admin/commerce/products", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: data.get("name"), slug: data.get("slug"), workspaceId: data.get("workspaceId") || null, description: data.get("description") || null }) }); await expectOk(response); form.reset(); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo crear"); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="grid gap-3 lg:grid-cols-4"><Input name="name" required placeholder="Nombre" /><Input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="slug-producto" /><Input name="workspaceId" pattern="[0-9a-fA-F-]{36}" placeholder="Workspace UUID (opcional)" /><Input name="description" maxLength={5000} placeholder="Descripción" /><div className="lg:col-span-4"><Button type="submit" disabled={busy}>{busy ? "Creando…" : "Crear producto"}</Button>{error ? <span className="ml-3 text-sm text-destructive">{error}</span> : null}</div></form>;
}

function ProductItem({ product }: { product: Product }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); const data = new FormData(event.currentTarget); try { const response = await fetch(`/api/admin/commerce/products/${product.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: data.get("name"), slug: data.get("slug"), description: data.get("description") || null, active: data.get("active") === "true", expectedVersion: product.version }) }); await expectOk(response); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo guardar"); } finally { setBusy(false); } }
  async function addPrice(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); const form = event.currentTarget; const data = new FormData(form); try { const response = await fetch(`/api/admin/commerce/products/${product.id}/prices`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ provider: data.get("provider"), amount: data.get("amount"), currency: data.get("currency"), interval: null, externalId: data.get("externalId") || null }) }); await expectOk(response); form.reset(); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo crear el precio"); } finally { setBusy(false); } }
  async function togglePrice(price: Price) { setBusy(true); setError(null); try { const response = await fetch(`/api/admin/commerce/prices/${price.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ active: !price.active, expectedVersion: price.version }) }); await expectOk(response); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "No se pudo cambiar el precio"); } finally { setBusy(false); } }
  return <article className="border-b border-border/70 py-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="text-xl font-semibold">{product.name}</h3><Badge variant={product.active ? "default" : "outline"}>{product.active ? "activo" : "inactivo"}</Badge></div><p className="mt-1 font-mono text-xs text-muted-foreground">{product.slug} · v{product.version} · {product.workspaceName ?? "global"}</p></div></div><form onSubmit={update} className="mt-5 grid gap-3 lg:grid-cols-[1fr_1fr_1.4fr_140px_auto]"><Input name="name" defaultValue={product.name} required /><Input name="slug" defaultValue={product.slug} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /><Input name="description" defaultValue={product.description ?? ""} placeholder="Descripción" /><select name="active" defaultValue={String(product.active)} className="h-11 rounded-lg border border-input bg-background px-3 text-sm"><option value="true">Activo</option><option value="false">Inactivo</option></select><Button type="submit" variant="outline" disabled={busy}>Guardar</Button></form><div className="mt-5 rounded-xl bg-muted/40 p-4"><h4 className="text-sm font-semibold">Precios de pago único</h4><div className="mt-2 divide-y divide-border/70">{product.prices.length === 0 ? <p className="py-3 text-sm text-muted-foreground">Sin precios.</p> : product.prices.map((price) => <div key={price.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-medium">{price.amount} {price.currency} · {price.provider}{price.interval ? ` / ${price.interval}` : ""}</p><p className="font-mono text-[11px] text-muted-foreground">{price.externalId ?? "sin external id"}</p></div><div className="flex items-center gap-2"><Badge variant={price.active ? "default" : "outline"}>{price.active ? "activo" : "inactivo"}</Badge><Button type="button" size="sm" variant="ghost" disabled={busy} onClick={() => togglePrice(price)}>{price.active ? "Desactivar" : "Activar"}</Button></div></div>)}</div><form onSubmit={addPrice} className="mt-4 grid gap-3 lg:grid-cols-[120px_1fr_100px_1.4fr_auto]"><select name="provider" defaultValue="stripe" className="h-11 rounded-lg border border-input bg-background px-3 text-sm"><option value="stripe">Stripe</option><option value="paypal">PayPal</option></select><Input name="amount" required inputMode="decimal" placeholder="19.00" /><Input name="currency" required minLength={3} maxLength={3} defaultValue="EUR" /><Input name="externalId" placeholder="Price ID del provider (opcional)" /><Button type="submit" disabled={busy}>Añadir pago único</Button></form></div>{error ? <p className="mt-3 text-sm text-destructive">{error}</p> : null}</article>;
}

export function CommerceManager({ products }: { products: Product[] }) { return <div className="divide-y divide-border/70">{products.length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">No hay productos.</p> : products.map((product) => <ProductItem key={product.id} product={product} />)}</div>; }
